#!/bin/bash
#

server=$1

docker stop $server >/dev/null 2>&1
docker rm $server >/dev/null 2>&1
rm -rf /etc/nginx/tmp_certs/$server

storage=/objectStorage/$server
mkdir -p $storage
chcon -Rt svirt_sandbox_file_t $storage

docker run \
	--name $server \
	-h $server \
	-p 443 -p 80 \
	-d \
	-v "$storage:/var/www/html/owncloud/data:rw" \
	-e VIRTUAL_HOST=$server \
	raghon/owncloud

ok=false
while [ $ok == "false" ] ; do
	ok=true	
	docker cp $server:/etc/httpd/ssl/server.crt /etc/nginx/tmp_certs/$server || ok=false
	docker cp $server:/etc/httpd/ssl/server.key /etc/nginx/tmp_certs/$server || ok=false
done

cp /etc/nginx/tmp_certs/$server/server.key /etc/nginx/certs/$server.key
cp /etc/nginx/tmp_certs/$server/server.crt /etc/nginx/certs/$server.crt

# Check if proxy is running:
proxy_running=$(docker inspect --format='{{.State.Running}}' proxy)
echo $proxy_running
if [ "${proxy_running}" != "true" ] ; then
	docker rm proxy
	docker run  -d --name proxy -h proxy --security-opt=label:type:docker_t -p 80:80 -p 443:443 -v /etc/nginx/certs:/etc/nginx/certs -v /var/run/docker.sock:/tmp/docker.sock jwilder/nginx-proxy
fi
